# Generated by Django 4.0.4 on 2022-05-06 17:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('services', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Клиент'),
        ),
        migrations.AddField(
            model_name='entry',
            name='spa',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='services.spa', verbose_name='Программа'),
        ),
        migrations.AddField(
            model_name='entry',
            name='staff',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='services.staff', verbose_name='Мастер'),
        ),
    ]
