# Generated by Django 4.0.4 on 2022-05-07 07:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('services', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DayEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_choice', models.CharField(choices=[('MO', 'Monday'), ('TU', 'Tuesday '), ('WE', 'Wednesday'), ('TH', 'Thursday'), ('FR', 'Friday'), ('SA', 'Saturday'), ('SU', 'Sunday')], max_length=2)),
                ('data', models.DateField(auto_now=True)),
            ],
            options={
                'verbose_name': 'День записи',
                'verbose_name_plural': 'День записи',
            },
        ),
        migrations.AlterModelOptions(
            name='entry',
            options={'verbose_name': 'Запись', 'verbose_name_plural': 'Записи'},
        ),
        migrations.CreateModel(
            name='TimeEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_entry', models.CharField(max_length=500)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('day_entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='services.dayentry')),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='services.staff')),
            ],
            options={
                'verbose_name_plural': 'Время записи',
            },
        ),
    ]
