# Generated by Django 4.0.4 on 2022-05-08 07:13

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0005_spa_image_alter_spa_slag'),
    ]

    operations = [
        migrations.AddField(
            model_name='spa',
            name='content',
            field=ckeditor_uploader.fields.RichTextUploadingField(default='', verbose_name='Рекламное описание'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='spa',
            name='body',
            field=ckeditor_uploader.fields.RichTextUploadingField(verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='spa',
            name='image',
            field=models.ImageField(upload_to=''),
        ),
    ]
