# Generated by Django 4.0.4 on 2022-05-08 07:13

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0006_spa_content_alter_spa_body_alter_spa_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spa',
            name='content',
            field=ckeditor_uploader.fields.RichTextUploadingField(default='', verbose_name='Рекламное описание'),
        ),
    ]
