# Generated by Django 4.0.4 on 2022-05-08 18:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0008_massage_alter_spa_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='massage',
            old_name='slag',
            new_name='slug',
        ),
    ]
